### ISSUE TITLE
[feature request] Add “Company Statistics by Repository Group” API

### ISSUE THREAD

**Issue by jonasrosland** [cncf/devstatscode#1]
Hi!

I think it could be very useful if we could query the API for “Company Statistics by Repository Group”, where we can specify custom time range and repository group.

Here's are example dashboards:
https://k8s.devstats.cncf.io/d/8/company-statistics-by-repository-group?orgId=1
and
https://harbor.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
Finished, new API described [here](https://github.com/cncf/devstatscode/blob/master/API.md) (search for `ComStatsRepoGrp`).
few example API calls via curl:
```
curl -H 'Content-Type: application/json' https://devstats.cncf.io/api/v1 -d'{"api":"ComStatsRepoGrp","payload":{"project":"Kubernetes","from":"2019-01-01","to":"2020-05-01","period":"Month","metric":"Contributors","repository_group":"SIG Apps","companies":["All"]}}' 2>/dev/null | jq
curl -H 'Content-Type: application/json' https://devstats.cncf.io/api/v1 -d'{"api":"ComStatsRepoGrp","payload":{"project":"Harbor","from":"2020-01-01","to":"2020-05-01","period":"Week","metric":"Contributions","repository_group":"All","companies":["VMware", "Independent", "Google", "Red Hat"]}}' 2>/dev/null | jq
```

An example call via [example script](https://github.com/cncf/devstatscode/blob/master/devel/api_com_stats_repo_grp.sh):
```
API_URL="https://devstats.cncf.io/api/v1" ./devel/api_com_stats_repo_grp.sh Harbor 2016-01-01 2020-01-01 Year Contributions 'goharbor/harbor' '["VMware", "Caicloud", "NetEase"]'
```

**Comment by lukaszgryglicki** [comment]
cc @jonasrosland
