### ISSUE TITLE
[bug] Invalid link at the https://devstats.cncf.io/ page to view the API

### ISSUE THREAD

**Issue by usmangt** [cncf/devstatscode#19]
When visiting https://devstats.cncf.io/

At the very bottom of the page where it says:

DevStats [API](https://devstats.cncf.io/api/v1),

After clicking on this link, gives:
`
{"error":"API 'unknown': EOF"}`

**Comment by lukaszgryglicki** [comment]
This is a REST API - URL is just an information where API lives, to actually use it - you need to call it from some program: https://github.com/cncf/devstatscode/blob/master/API.md
This is not a bug - calling API without specifying API name.
