### ISSUE TITLE
[bug] - devstats not respecting new affiliation of maintainers

### ISSUE THREAD

**Issue by OrlinVasilev** [cncf/devstatscode#24]
Hi team,
not sure if that's a bug indeed or misunderstanding on my side how devstat is feeding in information but, when I go to :
https://harbor.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20week&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=All

even just for one week my affiliation stays with my old company... maintainers.md updated and also https://github.com/cncf/foundation/pull/798
is updated.

Thank you so much!
Orlix

**Comment by lukaszgryglicki** [comment]
`cncf/foundation` is not synced in DevStats - you need to create a PR with affiliations update in `cncf/gitdm` - please follow [this guide](https://github.com/cncf/gitdm?tab=readme-ov-file#addingupdating-affiliation) and then wait up to 4 weeks for affiliations to refresh on all projects.
