### ISSUE TITLE
[feature request] Migration to golang Modules

### ISSUE THREAD

**Issue by hi-rustin** [cncf/devstatscode#6]
Are there any plans to migrate to golang Modules? So that we don't have to maintain the vendor.

**Comment by lukaszgryglicki** [comment]
Nope, you can delete vendor and use latest for all required deps.

**Comment by hi-rustin** [comment]
Got it, if you want to migrate I can help. If you don't want to you can feel free close the Issue now. Thanks for your reply!

**Comment by lukaszgryglicki** [comment]
I can do such a migration anytime, actually, you just reminded me about this. Will check this after the Holidays and probably just .gitignore all vendor deps (if they aren't gitignored now).

**Comment by hi-rustin** [comment]
reopen by https://github.com/cncf/devstatscode/pull/8#issuecomment-823388976
